FROM golang:latest AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY *.go ./
RUN go build -o /hello_go_http

# Create a new release build stage
FROM scratch
# Set the working directory to the root directory path
WORKDIR /
# Copy over the binary built from the previous stage
COPY --from=builder /hello_go_http /hello_go_http
ENTRYPOINT ["/hello_go_http"]